/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_menu (void);
GtkWidget* create_affichage_liste (void);
GtkWidget* create_ajout_liste (void);
GtkWidget* create_modification_liste (void);
GtkWidget* create_suppression_liste (void);
GtkWidget* create_statistique_liste (void);
GtkWidget* create_cherche_liste (void);
GtkWidget* create_dialog1 (void);
GtkWidget* create_bv_affichage (void);
GtkWidget* create_bv_ajouter (void);
GtkWidget* create_bv_modifier (void);
GtkWidget* create_dialog3 (void);
GtkWidget* create_bv_recherche (void);
GtkWidget* create_dialog4 (void);
GtkWidget* create_dialog5 (void);
GtkWidget* create_bv_statistique (void);
GtkWidget* create_accueil (void);
